### ISSUE TITLE
Missing JAR in the WPS download module (2.18.x)

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/geoserver#230]
I've opened this issue in [JIRA](https://osgeo-org.atlassian.net/browse/GEOS-9963) about 2 missing plugins in the packaging of the module:
- jackson-annotations-2.10.5
- jackson-databind-2.10.5
I tested this using GeoServer 2.18.2 and community modules 2.18.x.

**Comment by dromagnoli** [comment]
I see this from the JIRA log:
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
at org.geoserver.geopkg.wps.OWSContextWriter.<clinit>(OWSContextWriter.java:84)
at org.geoserver.geopkg.wps.GeoPackageProcess.execute(GeoPackageProcess.java:165)

Which makes me think about a problem with the gs-geopkg module instead of wps-download.
Checking the mvn dependency:tree output I also see no references of jackson-databind/annotations from wps-download while I see that in the geopackage one, coming from mbtiles:

[INFO] +- org.geoserver.community:gs-mbtiles:jar:2.18-SNAPSHOT:compile
[INFO] |  \- org.geotools:gt-mbtiles:jar:24-SNAPSHOT:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.5:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.5:compile

I'm going to fix the geopackage.
