### ISSUE TITLE
[GEOS-10006] Seeding GWC doesn't work for layers with a dot in the name

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#254]

**Comment by nmco** [comment]
Let's follow the usual workflow:

1. Time-box the initial investigation of the issue to 4 hours MAXIMUM.
2. Clarify the context of the task, make sure you have everything needed to move on.
3. Provide a plan and estimate to handle the reported issue, report on the issue.
4. Wait for the green light from the PM before moving on with the implementation.

**Comment by zvrablik** [comment]
I have reproduced with these steps
1. change name of existing layer e.g. topp:states to topp:states.my
2. go to gwc demo page http://localhost:8080/geoserver/gwc/demo and select seed this layer link of topp:states.my layers
3. http://localhost:8080/geoserver/gwc/rest/seed/topp:states.my got executed  with error message "Thread 184 Unknown layer topp:states. Check the logfiles, it may not have loaded properly."

log exception 
SEVERE: Thread 184 Unknown layer topp:states. Check the logfiles, it may not have loaded properly.
org.geowebcache.rest.exception.RestException 400 BAD_REQUEST: Thread 184 Unknown layer topp:states. Check the logfiles, it may not have loaded properly.
	at org.geowebcache.rest.service.FormService.handleGet(FormService.java:286)
	at org.geowebcache.rest.controller.SeedController.doFormGet(SeedController.java:79)
        .....

**Comment by zvrablik** [comment]
The issue is in [here](https://github.com/GeoWebCache/geowebcache/blob/ff28766b73ef5e7ac33b5e058a053af62910cb52/geowebcache/rest/src/main/java/org/geowebcache/rest/controller/SeedController.java#L81)
There should be used regex to avoid ignoring dot in the string path parameter @RequestMapping(value = "/seed/{layer:.+}",
as it is done in the post [here](https://github.com/GeoWebCache/geowebcache/blob/main/geowebcache/rest/src/main/java/org/geowebcache/rest/controller/SeedController.java#L104)

Plan:
1. modify GeoWebCache SeedController
2. manual testing, adding tests to SeedControllerTest page

4 hours ( I am not sure how easy it will be add and work locally with latest GeoWebCache), to get this finished I would need GeoWebCache release too. Will be ready to test after [release 2021-05-18](https://github.com/geoserver/geoserver/wiki/Release-Schedule)

@aaime Do you agree with the plan and estimates? What branches should this be backported to? GWC  1.18 and 1.19 ?

**Comment by aaime** [comment]
@zvrablik about readiness for testing, we also have [nightly builds](https://build.geoserver.org/geoserver/), waiting for a release is dangerous, something might slip past our attention and then the next release on the same branch happens two months later (or even 3, if the time span is across March and September, when we cut a new stable from development). 
Long story short, always push back against customers intending to only test in releases, tell them to use nightlies as soon as possible instead. If they are not the type that would follow our suggestions, plan manual testing against nightly builds yourself, accounting for that in the estimates.

About the backports, @nmco should confirm, but it's a bug fix, so I'd go for 1.18 and 1.19 indeed.

**Comment by zvrablik** [comment]
ok, I assume I would have to test this myself.

ok, I see that main branch of GeoServer is using main branch of GWC, so I am able to  do all without GWC release. Thanks.

@aaime are you ok with the 4 hours estimate?

**Comment by nmco** [comment]
Go ahead @zvrablik.

**Comment by zvrablik** [comment]
I have implemented the fix and I have integration test.
There is another test failing after implementing my fix [here](https://github.com/zvrablik/geowebcache/blob/ff28766b73ef5e7ac33b5e058a053af62910cb52/geowebcache/web/src/test/java/org/geowebcache/jetty/RestIntegrationTest.java#L1218-L1224)

I used this request http://localhost:8081/geowebcache/rest/seed/topp:states.xml

I am not sure why there is the .xml suffix. I did setup standalone GWC and did debug.
Layer is not found if used my fix for this issue. I don't see the .xml suffix used anywhere. Request is passed into FormService.handelGet, but it is not used inside. Only layer name is used. I don't see any filter while debugging standalone GWC.

@aaime should I try create pull request to see if it fails outside of my local env?

**Comment by aaime** [comment]
Sure you can give it a try. If it fails nothing bad happens and you get a confirmation.

**Comment by aaime** [comment]
Found we fought the same problem in the past here:

https://github.com/geoserver/geoserver/blob/main/src/restconfig/src/main/java/org/geoserver/rest/catalog/StructuredCoverageController.java#L167

Spring normally strips the suffix and uses it to decide which output format to use. But by changing the regex, we had to handle the eventual .xml/.json at the end of the name (check the filter construction) and also had to manually handle the choice of output format at the end of the method. As the comment says... "ugly as hell". 
I'm guessing the same issue is happening in the GeoServer REST API (the layer names are not using the `.+` regex) and that a more general fix would require fiddling with the Spring dispatcher.
[This stackoverflow question ](https://stackoverflow.com/questions/16332092/spring-mvc-pathvariable-with-dot-is-getting-truncated) might be of help. Do not stop at the first answer, scroll down, there is one that talks about keeping output fomat recognition while also allowsing dots in param names.
