### ISSUE TITLE
MapML projection selection for layer (and layergroup?) doesn't stick across server restart

### ISSUE THREAD

**Issue by prushforth** [geosolutions-it/geoserver#364]
To reproduce:

1) Set the states shapefile layer to MapML:CBMTILE, apply the projection, set the layer bounds to the projected value, save the definition, layer appears correct in preview.

2) Restart server.

In the startup logs, you will see:

```log
11 Mar 11:30:50 CONFIG [org.geoserver] - Loaded data store 'states_shapefile', enabled
11 Mar 11:30:50 WARN   [org.geoserver] - Error decode wkt: MapML:CBMTILE
org.geotools.api.referencing.FactoryException: Type "MAPML" is unknow in this context.
```

3) Go to the layers preview screen, select MapML preview link for states’ shapefile:

-  What should happen: the US States MapML preview should open in another tab.

- What actually happens: layers preview table reloads, the error below appears on the console:
```log
11 Mar 11:32:39 INFO   [web.demo] - Could not set figure out automatically a good preview link for topp:states
java.lang.RuntimeException: org.geotools.referencing.operation.projection.ProjectionException: Latitude 90°00.0'S is too close to a pole.
	at org.geoserver.wms.GetMapDefaults.autoSetBoundsAndSize(GetMapDefaults.java:143)
	at org.geoserver.wms.DefaultWebMapService.autoSetBoundsAndSize(DefaultWebMapService.java:334)
…

Caused by: org.geotools.referencing.operation.projection.ProjectionException: Latitude 90°00.0'S is too close to a pole.
	at org.geotools.referencing.operation.projection.LambertConformal.transformNormalized(LambertConformal.java:220)
	at org.geotools.referencing.operation.projection.MapProjection.transform(MapProjection.java:888)
	at org.geotools.referencing.operation.projection.MapProjection.transform(MapProjection.java:935)
	at org.geotools.referencing.operation.transform.AbstractMathTransform.transform(AbstractMathTransform.java:219)
	at org.geotools.referencing.EnvelopeReprojector.expandOnAxisExtremCrossing(EnvelopeReprojector.java:544)
	at org.geotools.referencing.EnvelopeReprojector.transform(EnvelopeReprojector.java:94)
	at org.geotools.referencing.CRS.transform(CRS.java:1519)
	at org.geotools.geometry.jts.ReferencedEnvelope.transform(ReferencedEnvelope.java:740)
	at org.geotools.geometry.jts.ReferencedEnvelope.transform(ReferencedEnvelope.java:684)
	at org.geoserver.catalog.impl.ResourceInfoImpl.boundingBox(ResourceInfoImpl.java:283)
	at jdk.internal.reflect.GeneratedMethodAccessor223.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.geoserver.catalog.impl.ModificationProxy.invoke(ModificationProxy.java:155)
	at com.sun.proxy.$Proxy49.boundingBox(Unknown Source)
	at org.geoserver.wms.MapLayerInfo.getBoundingBox(MapLayerInfo.java:175)
	at org.geoserver.wms.GetMapDefaults.autoSetBoundsAndSize(GetMapDefaults.java:129)
```

**Comment by prushforth** [comment]
Fixed
